
### Info page #########################################################

GET http://localhost:3001/info


### Get all persons ###################################################

GET http://localhost:3001/api/persons


### Return single entry ###############################################

@id = 2

GET http://localhost:3001/api/persons/{{id}}


### Delete person #####################################################

@id_to_delete = 2

DELETE http://localhost:3001/api/persons/{{id_to_delete}}


### Create person #####################################################

@new_person_name = Arto Huellas
@new_person_number = 123456

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "{{new_person_name}}",
    "number": "{{new_person_number}}"
}


#####################################################

